CREATE TABLE IF NOT EXISTS military_person (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    full_name  VARCHAR(255) NOT NULL,
    cpf        VARCHAR(255) NOT NULL,
    birth_date date,
    CONSTRAINT pk_military_person PRIMARY KEY (id)
);